package cn.xmu.edu.compuOrg.mapper;

import cn.xmu.edu.compuOrg.model.po.TestResultPo;
import cn.xmu.edu.compuOrg.model.po.TestResultPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface TestResultPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated
     */
    int insert(TestResultPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated
     */
    int insertSelective(TestResultPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated
     */
    List<TestResultPo> selectByExample(TestResultPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated
     */
    TestResultPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TestResultPo record, @Param("example") TestResultPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TestResultPo record, @Param("example") TestResultPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestResultPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestResultPo record);
}