package cn.xmu.edu.compuOrg.mapper;

import cn.xmu.edu.compuOrg.model.po.TopicResultPo;
import cn.xmu.edu.compuOrg.model.po.TopicResultPoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface TopicResultPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_result
     *
     * @mbg.generated
     */
    int insert(TopicResultPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_result
     *
     * @mbg.generated
     */
    int insertSelective(TopicResultPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_result
     *
     * @mbg.generated
     */
    List<TopicResultPo> selectByExample(TopicResultPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_result
     *
     * @mbg.generated
     */
    TopicResultPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_result
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TopicResultPo record, @Param("example") TopicResultPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_result
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TopicResultPo record, @Param("example") TopicResultPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TopicResultPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TopicResultPo record);
}