package cn.xmu.edu.compuOrg.model.po;

public class StaticMemPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_memory.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_memory.student_no
     *
     * @mbg.generated
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_memory.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_memory.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_memory.id
     *
     * @return the value of static_memory.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_memory.id
     *
     * @param id the value for static_memory.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_memory.student_no
     *
     * @return the value of static_memory.student_no
     *
     * @mbg.generated
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_memory.student_no
     *
     * @param studentNo the value for static_memory.student_no
     *
     * @mbg.generated
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_memory.address
     *
     * @return the value of static_memory.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_memory.address
     *
     * @param address the value for static_memory.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_memory.data
     *
     * @return the value of static_memory.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_memory.data
     *
     * @param data the value for static_memory.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}