package cn.xmu.edu.compuOrg.model.po;

import java.time.LocalDateTime;

public class TestPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.experiment_id
     *
     * @mbg.generated
     */
    private Long experimentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_content
     *
     * @mbg.generated
     */
    private String testContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.score
     *
     * @mbg.generated
     */
    private Byte score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.reference_version
     *
     * @mbg.generated
     */
    private String referenceVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.experiment_id
     *
     * @return the value of test.experiment_id
     *
     * @mbg.generated
     */
    public Long getExperimentId() {
        return experimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.experiment_id
     *
     * @param experimentId the value for test.experiment_id
     *
     * @mbg.generated
     */
    public void setExperimentId(Long experimentId) {
        this.experimentId = experimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.type
     *
     * @return the value of test.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.type
     *
     * @param type the value for test.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_content
     *
     * @return the value of test.test_content
     *
     * @mbg.generated
     */
    public String getTestContent() {
        return testContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_content
     *
     * @param testContent the value for test.test_content
     *
     * @mbg.generated
     */
    public void setTestContent(String testContent) {
        this.testContent = testContent == null ? null : testContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.img_url
     *
     * @return the value of test.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.img_url
     *
     * @param imgUrl the value for test.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.score
     *
     * @return the value of test.score
     *
     * @mbg.generated
     */
    public Byte getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.score
     *
     * @param score the value for test.score
     *
     * @mbg.generated
     */
    public void setScore(Byte score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.reference_version
     *
     * @return the value of test.reference_version
     *
     * @mbg.generated
     */
    public String getReferenceVersion() {
        return referenceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.reference_version
     *
     * @param referenceVersion the value for test.reference_version
     *
     * @mbg.generated
     */
    public void setReferenceVersion(String referenceVersion) {
        this.referenceVersion = referenceVersion == null ? null : referenceVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.gmt_create
     *
     * @return the value of test.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.gmt_create
     *
     * @param gmtCreate the value for test.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.gmt_modified
     *
     * @return the value of test.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.gmt_modified
     *
     * @param gmtModified the value for test.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}