package cn.xmu.edu.compuOrg.model.po;

import java.time.LocalDateTime;

public class TestResultPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.student_id
     *
     * @mbg.generated
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.experiment_id
     *
     * @mbg.generated
     */
    private Long experimentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_result.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.id
     *
     * @return the value of test_result.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.id
     *
     * @param id the value for test_result.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.student_id
     *
     * @return the value of test_result.student_id
     *
     * @mbg.generated
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.student_id
     *
     * @param studentId the value for test_result.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.experiment_id
     *
     * @return the value of test_result.experiment_id
     *
     * @mbg.generated
     */
    public Long getExperimentId() {
        return experimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.experiment_id
     *
     * @param experimentId the value for test_result.experiment_id
     *
     * @mbg.generated
     */
    public void setExperimentId(Long experimentId) {
        this.experimentId = experimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.score
     *
     * @return the value of test_result.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.score
     *
     * @param score the value for test_result.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.gmt_create
     *
     * @return the value of test_result.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.gmt_create
     *
     * @param gmtCreate the value for test_result.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_result.gmt_modified
     *
     * @return the value of test_result.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_result.gmt_modified
     *
     * @param gmtModified the value for test_result.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}