package cn.xmu.edu.compuOrg.model.po;

import java.time.LocalDateTime;

public class TopicPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.experiment_id
     *
     * @mbg.generated
     */
    private Long experimentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.score
     *
     * @mbg.generated
     */
    private Byte score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.reference_version
     *
     * @mbg.generated
     */
    private String referenceVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.experiment_id
     *
     * @return the value of topic.experiment_id
     *
     * @mbg.generated
     */
    public Long getExperimentId() {
        return experimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.experiment_id
     *
     * @param experimentId the value for topic.experiment_id
     *
     * @mbg.generated
     */
    public void setExperimentId(Long experimentId) {
        this.experimentId = experimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.type
     *
     * @return the value of topic.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.type
     *
     * @param type the value for topic.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.img_url
     *
     * @return the value of topic.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.img_url
     *
     * @param imgUrl the value for topic.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.score
     *
     * @return the value of topic.score
     *
     * @mbg.generated
     */
    public Byte getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.score
     *
     * @param score the value for topic.score
     *
     * @mbg.generated
     */
    public void setScore(Byte score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.reference_version
     *
     * @return the value of topic.reference_version
     *
     * @mbg.generated
     */
    public String getReferenceVersion() {
        return referenceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.reference_version
     *
     * @param referenceVersion the value for topic.reference_version
     *
     * @mbg.generated
     */
    public void setReferenceVersion(String referenceVersion) {
        this.referenceVersion = referenceVersion == null ? null : referenceVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.gmt_create
     *
     * @return the value of topic.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.gmt_create
     *
     * @param gmtCreate the value for topic.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.gmt_modified
     *
     * @return the value of topic.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.gmt_modified
     *
     * @param gmtModified the value for topic.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}